// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mktSolution.Data.EF;

namespace mktSolution.Data.Migrations
{
    [DbContext(typeof(MktDbContext))]
    [Migration("20201209062429_SeedDB")]
    partial class SeedDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("mktSolution.Data.Entities.SCM_Calendar", b =>
                {
                    b.Property<int>("IdCalendar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descreiption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeekNo")
                        .HasColumnType("int");

                    b.HasKey("IdCalendar");

                    b.ToTable("SCM_Calendar");

                    b.HasData(
                        new
                        {
                            IdCalendar = 1,
                            Date = new DateTime(2020, 12, 1, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            WeekNo = 0
                        },
                        new
                        {
                            IdCalendar = 2,
                            Date = new DateTime(2020, 12, 2, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            WeekNo = 0
                        },
                        new
                        {
                            IdCalendar = 3,
                            Date = new DateTime(2020, 12, 3, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            WeekNo = 0
                        },
                        new
                        {
                            IdCalendar = 4,
                            Date = new DateTime(2020, 12, 4, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            WeekNo = 0
                        },
                        new
                        {
                            IdCalendar = 5,
                            Date = new DateTime(2020, 12, 5, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            WeekNo = 0
                        },
                        new
                        {
                            IdCalendar = 6,
                            Date = new DateTime(2020, 12, 6, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            WeekNo = 0
                        },
                        new
                        {
                            IdCalendar = 7,
                            Date = new DateTime(2020, 12, 7, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            WeekNo = 0
                        });
                });

            modelBuilder.Entity("mktSolution.Data.Entities.SCM_Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 12, 9, 13, 24, 28, 440, DateTimeKind.Local).AddTicks(1711));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Order");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdOrder");

                    b.ToTable("SCM_Orders");

                    b.HasData(
                        new
                        {
                            IdOrder = 1,
                            CreateBy = 0,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 12, 1, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            ModelName = "A",
                            Qty = 1000,
                            Status = 0,
                            UpdateBy = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdOrder = 2,
                            CreateBy = 0,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 12, 3, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            ModelName = "B",
                            Qty = 2000,
                            Status = 0,
                            UpdateBy = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdOrder = 3,
                            CreateBy = 0,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 12, 5, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            ModelName = "A",
                            Qty = 1300,
                            Status = 0,
                            UpdateBy = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdOrder = 4,
                            CreateBy = 0,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2020, 12, 7, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            ModelName = "C",
                            Qty = 5000,
                            Status = 0,
                            UpdateBy = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("mktSolution.Data.Entities.SCM_Product", b =>
                {
                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 12, 9, 13, 24, 28, 455, DateTimeKind.Local).AddTicks(9110));

                    b.Property<DateTime>("DateProduct")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jobname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Plan");

                    b.Property<int>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdOrder", "IdProduct");

                    b.ToTable("SCM_Products");

                    b.HasData(
                        new
                        {
                            IdOrder = 1,
                            IdProduct = 1,
                            CreateBy = 0,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateProduct = new DateTime(2020, 12, 2, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            Jobname = "JN0001",
                            ModelName = "A",
                            Qty = 500,
                            Status = 0,
                            UpdateBy = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdOrder = 2,
                            IdProduct = 2,
                            CreateBy = 0,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateProduct = new DateTime(2020, 12, 3, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            Jobname = "JN0002",
                            ModelName = "B",
                            Qty = 800,
                            Status = 0,
                            UpdateBy = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdOrder = 1,
                            IdProduct = 3,
                            CreateBy = 0,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateProduct = new DateTime(2020, 12, 3, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            Jobname = "JN0003",
                            ModelName = "A",
                            Qty = 600,
                            Status = 0,
                            UpdateBy = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdOrder = 2,
                            IdProduct = 4,
                            CreateBy = 0,
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateProduct = new DateTime(2020, 12, 4, 10, 30, 50, 0, DateTimeKind.Unspecified),
                            Jobname = "JN0004",
                            ModelName = "B",
                            Qty = 1000,
                            Status = 0,
                            UpdateBy = 0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("mktSolution.Data.Entities.SCM_Product", b =>
                {
                    b.HasOne("mktSolution.Data.Entities.SCM_Order", "SCM_Order")
                        .WithMany("SCM_Product")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SCM_Order");
                });

            modelBuilder.Entity("mktSolution.Data.Entities.SCM_Order", b =>
                {
                    b.Navigation("SCM_Product");
                });
#pragma warning restore 612, 618
        }
    }
}
